#!/usr/bin/env python3
"""
img2game2d v2.0 Project Scaffolding Engine.
Generates production-grade 2D game asset workspaces with declarative configuration.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional


DEFAULT_CONFIG: Dict[str, Any] = {
    "$schema": "https://raw.githubusercontent.com/MrFaraidun/img2game2d/main/schemas/config.schema.json",
    "version": "2.0.0",
    "project": {
        "name": "my-game-project",
        "description": "2D Game Asset Workspace generated by img2game2d v2.0 Framework",
        "targetEngines": ["spine", "godot", "unity", "phaser", "pixijs"],
        "canvas": {
            "width": 576,
            "height": 512,
            "groundY": 460,
            "pivotX": 288
        }
    },
    "lighting": {
        "enabled": True,
        "normalStrength": 2.5,
        "invertY": False,
        "bloomEmission": True,
        "lumThreshold": 140.0,
        "satThreshold": 0.25
    },
    "atlas": {
        "powerOfTwo": True,
        "maxWidth": 2048,
        "maxHeight": 2048,
        "padding": 2
    },
    "animations": {
        "fpsDefaults": {
            "idle": 6,
            "run": 12,
            "jump": 7,
            "attack": 12,
            "defend": 8,
            "hurt": 6
        },
        "loopDefaults": {
            "idle": True,
            "run": True,
            "jump": False,
            "attack": False,
            "defend": False,
            "hurt": False
        }
    }
}


def scaffold_project(
    target_path: str | Path,
    project_name: Optional[str] = None,
    engines: Optional[List[str]] = None,
    interactive: bool = False,
) -> Dict[str, Any]:
    """Scaffolds a new img2game2d v2.0 project."""
    target_dir = Path(target_path).resolve()
    target_dir.mkdir(parents=True, exist_ok=True)

    name = project_name or target_dir.name or "my-2d-game"
    config = json.loads(json.dumps(DEFAULT_CONFIG))
    config["project"]["name"] = name
    if engines:
        config["project"]["targetEngines"] = engines

    # Create directory tree
    subdirs = [
        target_dir / "source",
        target_dir / "assets",
        target_dir / "exports" / "spine",
        target_dir / "exports" / "godot",
        target_dir / "exports" / "unity",
        target_dir / "exports" / "phaser",
        target_dir / "exports" / "viewer",
    ]
    for sd in subdirs:
        sd.mkdir(parents=True, exist_ok=True)

    # Write declarative config
    config_file = target_dir / "img2game2d.config.json"
    with open(config_file, "w", encoding="utf-8") as f:
        json.dump(config, f, indent=2)

    # Write project README
    readme_content = f"""# {name}

2D Game Asset Workspace generated by **img2game2d v2.0 Framework**.

## Quick Start
```bash
# 1. Place character concept art or multi-pose sheet in source/
# 2. Run dev studio with live hot-reloading
img2game2d dev

# 3. Build all exports (Godot, Unity, Spine 2D, Phaser)
img2game2d build
```

## Configuration
Edit `img2game2d.config.json` to configure:
- Canvas dimensions & ground anchor ($Y=460$)
- 2D Dynamic Lighting (Normal maps & Bloom Emission)
- Animation FPS & loop rules
- Target engine exporters
"""
    (target_dir / "README.md").write_text(readme_content, encoding="utf-8")

    return {
        "status": "success",
        "project_name": name,
        "path": str(target_dir),
        "config": str(config_file),
    }


def main():
    parser = argparse.ArgumentParser(description="Scaffold a new img2game2d v2.0 project")
    parser.add_argument("name", nargs="?", default="my-game-project", help="Project directory name")
    parser.add_argument("--engines", default=None, help="Comma-separated target engines (e.g. godot,spine,unity)")
    parser.add_argument("--dir", default=None, help="Target directory (defaults to current dir / name)")
    args = parser.parse_args()

    dest = Path(args.dir) if args.dir else Path.cwd() / args.name
    engines_list = [e.strip() for e in args.engines.split(",")] if args.engines else None

    print(f"\n🚀 Scaffolding img2game2d v2.0 Framework project in {dest}...")
    res = scaffold_project(dest, project_name=args.name, engines=engines_list)
    print(f"✓ Created: {res['config']}")
    print("✓ Project initialized successfully!")
    print(f"\nNext steps:\n  cd {res['path']}\n  img2game2d dev\n")


if __name__ == "__main__":
    main()
