"""
Phaser 3 exporter for img2game2d.

Generates:
    exports/phaser/
    ├── atlases/            — Atlas PNGs (copy from atlases/)
    ├── <assetId>.json      — Phaser atlas JSON (TexturePacker format)
    ├── <assetId>.ts        — TypeScript loader + animation config
    └── README.md
"""
from __future__ import annotations

import json
import shutil
from pathlib import Path


class PhaserExporter:
    """Exports game assets as Phaser 3 atlas + TypeScript animation config."""

    def export(self, asset: dict, atlases_dir: str, out_dir: str) -> dict:
        out_path = Path(out_dir)
        out_path.mkdir(parents=True, exist_ok=True)
        atlases_path = Path(atlases_dir)

        asset_id = asset.get("asset_id", "unnamed")
        asset_name = asset.get("name", asset_id)
        animations = asset.get("animations", {})

        # Copy atlas PNGs into export
        export_atlases = out_path / "atlases"
        export_atlases.mkdir(exist_ok=True)
        for png in atlases_path.glob("*.png"):
            shutil.copy2(str(png), str(export_atlases / png.name))

        # Build unified Phaser atlas JSON (all clips merged)
        phaser_atlas: dict = {
            "textures": [],
            "meta": {
                "app": "img2game2d",
                "format": "RGBA8888",
                "asset": asset_id,
            },
        }

        atlas_summary_path = atlases_path / "atlas_summary.json"
        if atlas_summary_path.exists():
            with open(atlas_summary_path) as f:
                atlas_summary = json.load(f)
        else:
            atlas_summary = {}

        for clip_name, clip_data in atlas_summary.items():
            atlas_json_path = atlases_path / f"{clip_name}.json"
            if not atlas_json_path.exists():
                continue
            with open(atlas_json_path) as f:
                atlas_data = json.load(f)

            meta = atlas_data.get("meta", {})
            frames = atlas_data.get("frames", [])

            texture_entry: dict = {
                "image": f"atlases/{clip_name}.png",
                "format": "RGBA8888",
                "size": meta.get("size", {"w": 512, "h": 512}),
                "scale": 1,
                "frames": [],
            }

            for i, frame in enumerate(frames):
                r = frame.get("frame", {})
                texture_entry["frames"].append({
                    "filename": f"{clip_name}_{i:03d}",
                    "frame": {"x": r.get("x", 0), "y": r.get("y", 0), "w": r.get("w", 64), "h": r.get("h", 64)},
                    "rotated": False,
                    "trimmed": False,
                    "spriteSourceSize": {"x": 0, "y": 0, "w": r.get("w", 64), "h": r.get("h", 64)},
                    "sourceSize": frame.get("sourceSize", {"w": 64, "h": 64}),
                })

            phaser_atlas["textures"].append(texture_entry)

        atlas_out = out_path / f"{asset_id}.json"
        with open(atlas_out, "w") as f:
            json.dump(phaser_atlas, f, indent=2)

        # TypeScript loader
        ts_content = self._build_typescript(asset_id, asset_name, animations, atlas_summary)
        ts_out = out_path / f"{asset_id}.ts"
        ts_out.write_text(ts_content)

        # README
        (out_path / "README.md").write_text(self._build_readme(asset_id, asset_name))

        return {
            "engine": "phaser",
            "files": [str(atlas_out), str(ts_out)],
            "atlas_json": str(atlas_out),
            "typescript": str(ts_out),
        }

    def _build_typescript(self, asset_id: str, asset_name: str, animations: dict, atlas_summary: dict) -> str:
        anim_entries: list[str] = []
        for clip_name, anim_config in animations.items():
            fps = anim_config.get("fps", 12)
            loop = str(anim_config.get("loop", True)).lower()
            frame_count = atlas_summary.get(clip_name, {}).get("frame_count", 4)
            frames = ", ".join(f'"{clip_name}_{i:03d}"' for i in range(frame_count))
            anim_entries.append(f"""  {{
    key: "{asset_id}_{clip_name}",
    frames: [{frames}],
    frameRate: {fps},
    repeat: {-1 if loop == "true" else 0},
  }}""")

        anims_str = ",\n".join(anim_entries)

        return f"""/**
 * {asset_name} — Phaser 3 asset loader
 * Generated by img2game2d
 */

export const {asset_id.upper()}_ANIMATIONS = [
{anims_str}
];

/**
 * Load all {asset_name} atlases in your Phaser Scene.preload():
 */
export function preload{asset_name.replace(" ", "")}(scene: Phaser.Scene): void {{
  // Load individual clip atlases
  scene.load.atlas(
    "{asset_id}",
    "assets/{asset_id}/{asset_id}.json",
    // Phaser will load the image referenced in the atlas JSON
  );
}}

/**
 * Create animations in your Phaser Scene.create():
 */
export function create{asset_name.replace(" ", "")}Animations(scene: Phaser.Scene): void {{
  {asset_id.upper()}_ANIMATIONS.forEach((anim) => {{
    if (!scene.anims.exists(anim.key)) {{
      scene.anims.create({{
        key: anim.key,
        frames: anim.frames.map((f) => ({{ key: "{asset_id}", frame: f }})),
        frameRate: anim.frameRate,
        repeat: anim.repeat,
      }});
    }}
  }});
}}
"""

    def _build_readme(self, asset_id: str, asset_name: str) -> str:
        return f"""# {asset_name} — Phaser 3 Export

## Files
- `atlases/` — Atlas PNG textures
- `{asset_id}.json` — Phaser atlas JSON (multi-texture format)
- `{asset_id}.ts` — TypeScript loader and animation config

## Usage

```typescript
import {{ preload{asset_name.replace(' ', '')}, create{asset_name.replace(' ', '')}Animations }} from './{asset_id}';

class GameScene extends Phaser.Scene {{
  preload() {{
    preload{asset_name.replace(' ', '')}(this);
  }}

  create() {{
    create{asset_name.replace(' ', '')}Animations(this);
    const sprite = this.add.sprite(400, 300, '{asset_id}');
    sprite.play('{asset_id}_idle');
  }}
}}
```

Generated by img2game2d
"""
