"""
PixiJS exporter for img2game2d.

Generates:
    exports/pixijs/
    ├── atlases/            — Atlas PNGs
    ├── <assetId>.json      — PixiJS spritesheet JSON
    ├── <assetId>.ts        — TypeScript loader + AnimatedSprite config
    └── README.md
"""
from __future__ import annotations

import json
import shutil
from pathlib import Path


class PixiJSExporter:
    """Exports game assets as PixiJS AnimatedSprite-compatible atlas + TypeScript metadata."""

    def export(self, asset: dict, atlases_dir: str, out_dir: str) -> dict:
        out_path = Path(out_dir)
        out_path.mkdir(parents=True, exist_ok=True)
        atlases_path = Path(atlases_dir)

        asset_id = asset.get("asset_id", "unnamed")
        asset_name = asset.get("name", asset_id)
        animations = asset.get("animations", {})

        # Copy atlas PNGs
        export_atlases = out_path / "atlases"
        export_atlases.mkdir(exist_ok=True)
        for png in atlases_path.glob("*.png"):
            shutil.copy2(str(png), str(export_atlases / png.name))

        # PixiJS spritesheet JSON (per animation clip)
        atlas_summary_path = atlases_path / "atlas_summary.json"
        if atlas_summary_path.exists():
            with open(atlas_summary_path) as f:
                atlas_summary = json.load(f)
        else:
            atlas_summary = {}

        pixi_sheets: dict = {}

        for clip_name, clip_data in atlas_summary.items():
            atlas_json_path = atlases_path / f"{clip_name}.json"
            if not atlas_json_path.exists():
                continue
            with open(atlas_json_path) as f:
                atlas_data = json.load(f)

            frames_dict: dict = {}
            for i, frame in enumerate(atlas_data.get("frames", [])):
                r = frame.get("frame", {})
                key = f"{clip_name}_{i:03d}.png"
                frames_dict[key] = {
                    "frame": {"x": r.get("x", 0), "y": r.get("y", 0), "w": r.get("w", 64), "h": r.get("h", 64)},
                    "rotated": False,
                    "trimmed": False,
                    "spriteSourceSize": {"x": 0, "y": 0, "w": r.get("w", 64), "h": r.get("h", 64)},
                    "sourceSize": frame.get("sourceSize", {"w": 64, "h": 64}),
                }

            meta = atlas_data.get("meta", {})
            size = meta.get("size", {"w": 512, "h": 512})

            pixi_sheets[clip_name] = {
                "frames": frames_dict,
                "meta": {
                    "image": f"atlases/{clip_name}.png",
                    "format": "RGBA8888",
                    "size": size,
                    "scale": "1",
                },
            }

        # Write individual pixi JSON per clip
        for clip_name, sheet_data in pixi_sheets.items():
            clip_json_path = out_path / f"{asset_id}_{clip_name}.json"
            with open(clip_json_path, "w") as f:
                json.dump(sheet_data, f, indent=2)

        # TypeScript loader
        ts_content = self._build_typescript(asset_id, asset_name, animations, atlas_summary)
        ts_path = out_path / f"{asset_id}.ts"
        ts_path.write_text(ts_content)

        # README
        (out_path / "README.md").write_text(self._build_readme(asset_id, asset_name))

        return {
            "engine": "pixijs",
            "files": [str(ts_path)],
            "typescript": str(ts_path),
            "clip_count": len(pixi_sheets),
        }

    def _build_typescript(self, asset_id: str, asset_name: str, animations: dict, atlas_summary: dict) -> str:
        clip_loaders: list[str] = []
        anim_keys: list[str] = []

        for clip_name in atlas_summary:
            anim_keys.append(f'"{clip_name}"')
            frame_count = atlas_summary[clip_name].get("frame_count", 4)
            clip_loaders.append(
                f'  loader.add("{asset_id}_{clip_name}", `${{basePath}}/{asset_id}_{clip_name}.json`);'
            )

        fps_map: dict = {
            c: animations.get(c, {}).get("fps", 12) for c in atlas_summary
        }
        fps_entries = "\n".join(
            f'  "{c}": {fps_map[c]},' for c in fps_map
        )

        return f"""/**
 * {asset_name} — PixiJS AnimatedSprite loader
 * Generated by img2game2d
 */
import * as PIXI from "pixi.js";

export type {asset_id.capitalize()}Animation = {" | ".join(anim_keys)};

export const {asset_id.upper()}_FPS: Record<string, number> = {{
{fps_entries}
}};

/**
 * Load all {asset_name} sprite sheets.
 * @param loader - PIXI.Loader instance
 * @param basePath - Path to the pixijs export directory
 */
export function load{asset_name.replace(" ", "")}(loader: PIXI.Loader, basePath = "assets/{asset_id}/pixijs"): void {{
{chr(10).join(clip_loaders)}
}}

/**
 * Create an AnimatedSprite for the given animation clip.
 * Call after all sheets are loaded.
 */
export function create{asset_name.replace(" ", "")}Sprite(
  clip: {asset_id.capitalize()}Animation,
  autoPlay = true,
): PIXI.AnimatedSprite {{
  const sheet = PIXI.Loader.shared.resources[`{asset_id}_${{clip}}`]?.spritesheet;
  if (!sheet) throw new Error(`Spritesheet for "{asset_id}_${{clip}}" not loaded`);

  const frames = Object.values(sheet.textures);
  const sprite = new PIXI.AnimatedSprite(frames as PIXI.Texture[]);
  sprite.animationSpeed = ({asset_id.upper()}_FPS[clip] ?? 12) / 60;
  sprite.anchor.set(0.5, 0.5);
  if (autoPlay) sprite.play();
  return sprite;
}}
"""

    def _build_readme(self, asset_id: str, asset_name: str) -> str:
        return f"""# {asset_name} — PixiJS Export

## Files
- `atlases/` — Atlas PNG textures
- `{asset_id}_<clip>.json` — Per-clip PixiJS spritesheet JSON
- `{asset_id}.ts` — TypeScript loader and AnimatedSprite factory

## Usage

```typescript
import {{ load{asset_name.replace(' ', '')}, create{asset_name.replace(' ', '')}Sprite }} from './{asset_id}';

const app = new PIXI.Application();

PIXI.Loader.shared
  .add('{asset_id}')
  .load(() => {{
    load{asset_name.replace(' ', '')}(PIXI.Loader.shared);
    PIXI.Loader.shared.load(() => {{
      const sprite = create{asset_name.replace(' ', '')}Sprite('idle');
      app.stage.addChild(sprite);
    }});
  }});
```

Generated by img2game2d
"""
