"""
Unity exporter for img2game2d.

Generates:
    exports/unity/
    ├── <AssetName>_sprites/     — Frame PNGs (copy to Assets/)
    ├── <AssetName>_atlas.json   — Atlas metadata
    ├── <AssetName>_animator.json — AnimatorController stub (import via custom editor tool)
    └── README.md
"""
from __future__ import annotations

import json
import shutil
from pathlib import Path


class UnityExporter:
    """Exports game assets as Unity-compatible sprite + animator metadata."""

    def export(self, asset: dict, atlases_dir: str, out_dir: str) -> dict:
        out_path = Path(out_dir)
        out_path.mkdir(parents=True, exist_ok=True)
        atlases_path = Path(atlases_dir)

        asset_id = asset.get("asset_id", "unnamed")
        asset_name = asset.get("name", asset_id).replace(" ", "")
        animations = asset.get("animations", {})

        # Copy atlas PNGs
        sprites_dir = out_path / f"{asset_name}_sprites"
        sprites_dir.mkdir(exist_ok=True)

        copied_atlases: list[str] = []
        for atlas_png in atlases_path.glob("*.png"):
            dest = sprites_dir / atlas_png.name
            shutil.copy2(str(atlas_png), str(dest))
            copied_atlases.append(atlas_png.name)

        # Atlas JSON (Unity Texture Packer-compatible format)
        atlas_summary_path = atlases_path / "atlas_summary.json"
        atlas_summary = {}
        if atlas_summary_path.exists():
            with open(atlas_summary_path) as f:
                atlas_summary = json.load(f)

        unity_atlas: dict = {"animations": {}}
        for clip_name, clip_data in atlas_summary.items():
            atlas_json_path = atlases_path / f"{clip_name}.json"
            if atlas_json_path.exists():
                with open(atlas_json_path) as f:
                    atlas_data = json.load(f)
                unity_atlas["animations"][clip_name] = {
                    "atlas": f"{asset_name}_sprites/{clip_name}.png",
                    "fps": atlas_data.get("meta", {}).get("fps", 12),
                    "loop": atlas_data.get("meta", {}).get("loop", True),
                    "frames": atlas_data.get("frames", []),
                }

        atlas_json_path = out_path / f"{asset_name}_atlas.json"
        with open(atlas_json_path, "w") as f:
            json.dump(unity_atlas, f, indent=2)

        # AnimatorController stub (JSON — import via Unity editor script)
        animator: dict = {
            "name": f"{asset_name}Controller",
            "defaultState": "idle",
            "states": [],
        }
        for clip_name, anim_config in animations.items():
            state: dict = {
                "name": clip_name,
                "clip": f"{clip_name}",
                "speed": 1.0,
                "loop": anim_config.get("loop", True),
                "transitions": [],
            }
            animator["states"].append(state)

        animator_path = out_path / f"{asset_name}_animator.json"
        with open(animator_path, "w") as f:
            json.dump(animator, f, indent=2)

        # README
        readme = f"""# {asset_name} — Unity Export

## Files
- `{asset_name}_sprites/` — Atlas PNG files. Import into Unity as Sprite (Multiple).
- `{asset_name}_atlas.json` — Frame metadata for each animation clip.
- `{asset_name}_animator.json` — AnimatorController stub.

## Setup
1. Copy `{asset_name}_sprites/` into your Unity project under `Assets/Sprites/{asset_name}/`.
2. Set each PNG's Sprite Mode to **Multiple** in the Inspector.
3. Use the frame data from `{asset_name}_atlas.json` to slice sprites (or use Sprite Editor).
4. Create AnimationClips using the frame slices.
5. Reference `{asset_name}_animator.json` to set up AnimatorController state machine.

Generated by img2game2d
"""
        (out_path / "README.md").write_text(readme)

        return {
            "engine": "unity",
            "files": [str(atlas_json_path), str(animator_path)],
            "sprites_dir": str(sprites_dir),
            "atlas_json": str(atlas_json_path),
            "animator": str(animator_path),
        }
